(let* ((win (instantiate::window
	       (title "An example of gauge")
	       (height 80)
	       (width 200)))
       (gauge1 (instantiate::gauge
		  (parent win)
		  (style '(value discrete))
		  (height 20)))
       (gauge2 (instantiate::gauge
		  (parent win)
		  (style '(value text))
		  (height 20)
		  (value 100)
		  (text "A user text")))
       (gauge3 (instantiate::gauge
		  (parent win)
		  (style 'activity)
		  (height 20)))
       (anim? #t)
       (i 0)
       (delta -2)
       (thunk (lambda ()
		 (cond
		    ((=fx i 100)
		     (set! delta (- delta)))
		    ((=fx i 0)
		     (set! delta (- delta))))
		 (set! i (+fx i delta))
		 (gauge-value-set! gauge1 i)
		 (gauge-value-set! gauge2 (-fx 100 i))
		 (gauge-value-set! gauge3 (-fx 100 i))
		 anim?))
       (stop (instantiate::check-button
		(parent win)
		(text "Animate")
		(command (lambda (e)
			    (let* ((w (event-widget e))
				   (v (check-button-on w)))
			       (set! anim? v)
			       (if v (timeout 100 thunk))))))))
   (print "gauge1: " gauge1))
